name: Bug Report
description: File a bug report
body:
  - type: textarea
    attributes:
      label: Diagnostic
      description: Run `!gddiagnostic` in Alfred. After the notification/sound, paste into this box
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Debugger output
      description: Open the Workflow in Alfred Preferences → click the bug icon → perform the failing action
      render: codeblock
    validations:
      required: true
  - type: textarea
    attributes:
      label: More details
      description: Explain what you did, what happened, and what you expected to happen
