#!/usr/bin/ruby
# frozen_string_literal: true

require 'json'
require 'pathname'
require 'sqlite3'

Gdrive_paths = if ENV['google_drive_path'].nil? || ENV['google_drive_path'].empty?
  [Pathname.new('/Volumes/GoogleDrive/My Drive')]
else
  ENV['google_drive_path'].split(',').map { |p| Pathname.new(p.strip).expand_path }
end

unless Gdrive_paths.all?(&:exist?)
  print 'PATH_ERROR' # For Alfred's conditional
  abort 'Google Drive path does not exist!' # For Alfred's debugger
end

Ignores = ENV['ignore_list'].split(',').map(&:strip) rescue []
Tmp_file = Pathname.new(ENV['alfred_workflow_cache']).join('tmp_db')
Cache_file = Pathname.new(ENV['alfred_workflow_cache']).join('cache.db')
Cache_file.dirname.mkpath

if Tmp_file.exist?
  print 'ONGOING_REBUILD' # For Alfred's conditional
  abort 'Cache creation already in progress' # For Alfred's debugger
end

db = SQLite3::Database.new(Tmp_file.to_path)
db.execute('CREATE TABLE main (fullpath TEXT, basename TINYTEXT, isdir BOOLEAN, accesstime INTEGER);')

Gdrive_paths.each do |gdrive_path|
  gdrive_path.glob('**/*').each do |path|
    next if path.symlink?
    next if Ignores.any? { |i| path.include?(i) }

    accesstime = path.atime.to_i rescue next
    fullpath = path.to_path
    basename = path.basename.to_path
    isdir = path.directory? ? 1 : 0

    db.execute('INSERT INTO main (fullpath, basename, isdir, accesstime) VALUES (?, ?, ?, ?);', [fullpath, basename, isdir, accesstime])
  end
end

Tmp_file.rename(Cache_file)
