#!/usr/bin/ruby

require 'json'
require 'pathname'
require 'sqlite3'

Gdrive_path = (ENV['google_drive_path'].nil? || ENV['google_drive_path'].empty?) ? Pathname.new('/Volumes/GoogleDrive/My Drive') : Pathname.new(ENV['google_drive_path'])
Ignores = ENV['ignore_list'].split(',').map(&:strip) rescue []
Tmp_file = Pathname.new(ENV['alfred_workflow_cache']).join('tmp_db')
Cache_file = Pathname.new(ENV['alfred_workflow_cache']).join('cache.db')
Cache_file.dirname.mkpath

db = SQLite3::Database.new(Tmp_file.to_path)
db.execute('CREATE TABLE main (fullpath TEXT, basename TINYTEXT, accesstime INTEGER);')

Gdrive_path.glob('**/*').each do |path|
  next if path.symlink?
  next if Ignores.any? { |i| path.include?(i) }

  accesstime = path.atime.to_i
  basename = path.basename.to_path
  path_string = path.to_path

  db.execute("INSERT INTO main (fullpath, basename, accesstime) VALUES (?, ?, ?);", [path_string, basename, accesstime])
end

Tmp_file.rename(Cache_file)
